### ISSUE TITLE
Do you know why w-full doesn't show up for tailwind?

### ISSUE THREAD

**Issue by mastoj** [zanaptak/TypedCssClasses#10]
Thank you for the samples. I've cloned this one and played around with it, for some reason I can' get `w-full` to work with the type provider. From what I can see `w-full` is part of the "utilities", but for some reason it isn't generated in the provider.

Any clue what is going on?

**Comment by zanaptak** [comment]
`w-full` works for me in the [FableTailwind](https://github.com/zanaptak/TypedCssClasses/tree/main/sample/FableTailwind) sample, so it is probably something with your Tailwind configuration. Try using the Tailwind CLI and generating CSS file manually to make sure it is including the expected classes.

![tailwind wfull](https://user-images.githubusercontent.com/53196138/114470040-d0d4f280-9bb3-11eb-8ef6-c8cfccc0010b.gif)
