### ISSUE TITLE
Setting environment variables for a command

### ISSUE THREAD

**Issue by NickDarvey** [zanaptak/TypedCssClasses#13]
I understand I can [use environment variables](https://github.com/zanaptak/TypedCssClasses/blob/main/doc/configuration.md#environment-variables) in command parameters, but is there a way to specify environment variables?

My use case is setting `TS_NODE_PROJECT` to point ts-node to a tsconfig.json.

**Comment by zanaptak** [comment]
No, not directly in the type provider. I would recommend using a script (node, bash, powershell, etc.) to set up the environment and call your command. For example see the [FableTailwind](https://github.com/zanaptak/TypedCssClasses/tree/main/sample/FableTailwind) sample, where we could have hypothetically called the Tailwind CLI directly, but instead we are calling a tailwind-process.js script and passing in a config filename. You could do something similar and set environment variables as needed from the script arguments.

**Comment by NickDarvey** [comment]
Makes sense, thanks @zanaptak
